### ISSUE TITLE
互信息上界交流

### ISSUE THREAD

**Issue by junkangwu** [Wendison/E2E-DSR-demo#1]
抱歉打扰您～
我是在2020ICML-CLUB模型的issue中看到您和我有类似的训练问题，请问能否添加一个联系方向交流一下最小化互信息上界实现disentangle的思想？我训练自己模型中也出现了无法收敛的问题，具体情况为：
- 按照club论文及其中例子所示，第一步训练log likehood q(y|x),此时应当将encoder模型参数固定，而开放CLUB互信息学习模型参数；而第二部计算分类生成损失以及互信息上界时，此时CLUB参数应当固定，更新encoder参数。我一开始并没有对训练过程中参数进行固定或者开放，出现的情况为，upbound_loss从正逐渐降低，并且变为负数一直无法收敛；而今天意识到参数学习次序，即有选择性释放或者固定相应模型参数时，lld_loss维持在很高的水平（50左右）而互信息上界则由正数变为负数到-4慢慢从负数方向靠近0值附近。
- 请问您目前相关研究进展怎样，如果有相同类似的目的，希望能够一起交流学习学习！感谢！

如有打扰，请多包涵！

**Comment by Wendison** [comment]
你好，我目前的情况和你差不多，lld_loss还要更高一些，刚开始从大概-50到最终130，最后会稳定在130左右。互信息上界一直在0附近，大概在1e-3或更小的量级，不同的epoch会是负或正。目前的结果是用了MI minimization要比不用效果好一些。有2个trick可以给你参考下: (1) CLUB-net可以多训几个step，比如CLUB-net训练5个step，然后encoder只训练1个step；(2) MI-loss乘以0.1加到encoder原有loss中进行训练。感觉这个方法比较task-specific，对于不同的任务需要多调下参数，比如网络结构，hidden size, activation function, learning rate之类的。

**Comment by junkangwu** [comment]
你好呀！
1. 我想问问训练我第一点中参数固定及释放的理解顺序没错吧？
2. 你训练时候lld_loss这么大？但是我主要的问题是互信息上界似乎一直是负的，就一开始正的变为负数，后续又慢慢收敛回来了，但仍然是负数，即训练过程中所有互信息上界都是负数，这就让我怀疑自己自己模型有效性了，因为按理说互信息应当是正数吧？
3. 谢谢你啦！我去试试你的建议哈！

祝好

**Comment by Wendison** [comment]
1. 对的；
2. 有可能是负数，我的理解是计算的互信息上界只是一个估计值，CLUB-net没有学好，就会存在为负的情况。

**Comment by junkangwu** [comment]
感谢！我去试试！
